version: '3.8'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
    - 27017:27017
    networks:
    - ldes

  data_pipeline:
    environment:
      DEBUG: "*"
      MONGO: "mongodb://mongodb:27017/data"
    build: 
      context: ..
      dockerfile: ./docker/pipeline.yml
    volumes:
      - ../data:/workspace/data
    command: /workspace/data/data_pipeline.ttl
    networks:
    - ldes
    depends_on:
    - mongodb

  nodes_pipeline:
    environment:
      DEBUG: "*"
      MONGO: "mongodb://mongodb:27017/nodes"
    build: 
      context: ..
      dockerfile: ./docker/pipeline.yml
    volumes:
      - ../nodes:/workspace/nodes
    command: /workspace/nodes/nodes_pipeline.ttl
    networks:
    - ldes
    depends_on:
    - mongodb

  ldesserver:
    build:
      context: ldes
      dockerfile: ./Dockerfile
    volumes:
      - ./ldes/data:/ldes-solid-server/data
    command: -f ./data -b http://localhost:3000
    networks:
      - ldes
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    restart: always

networks:
    ldes:
