version: '3.8'
include:
  - ../docker-servers.yaml
services:

  data_pipeline:
    environment:
      # REDIS: "redis://redis-ldes:6379/"
      REDIS: "mongodb://mongo:27017/data"
      KAFKA: "kafka:19092"
    build: 
      context: ..
      dockerfile: ./docker/pipeline.yml
    # volumes:
    #   - ../data:/workspace/data
    command: /workspace/data/data_pipeline.ttl
    depends_on:
      # - redis-nodes
      - init-kafka
      # - redis-ldes
      - mongo

  nodes_pipeline:
    environment:
      # REDIS: "redis://redis-nodes:6379/"
      REDIS: "mongodb://mongo:27017/nodes"
    build: 
      context: ..
      dockerfile: ./docker/pipeline.yml
    # volumes:
    #   - ../nodes:/workspace/nodes
    command: /workspace/nodes/nodes_pipeline.ttl
    depends_on:
      # - redis-nodes
      - mongo

  ldesserver:
    build:
      context: ldes
      dockerfile: ./Dockerfile
    volumes:
      - ./ldes/data:/ldes-solid-server/data
      - ./ldes/config-ldes.json:/ldes-solid-server/config-ldes.json
    command: -f ./data -b http://localhost:3000 -l debug
    depends_on:
      - mongo
      # - redis-nodes
      # - redis-ldes
    ports:
      - 3000:3000
    restart: always
